#!/usr/bin/python
import numpy as np
import matplotlib.pyplot as plt
import os
import sys
import argparse
from munge import write_normalised_png
from meta import read_info_json, CLUSTERINESS

from eval import load_clustering_json, load_ranking_json


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('-i', '--input', help='load this json')

    parser.add_argument('-o', '--output', help='write png here')

    args = parser.parse_args()
    
    data = load_ranking_json(args.input)

    names = set()
    for score, links in data:
        names.update(links)

    names = sorted(names)

    w = len(names)
    img = np.zeros((w, w))
    name_lut = {k:i for i, k in enumerate(names)}
    for score, link in data:
        x = name_lut[link[0]]
        y = name_lut[link[1]]
        img[x, y] = score
        img[y, x] = score

    write_normalised_png(img, args.output, negative=True)

main()
